name: price_checker_2
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.8
  responsive_sizer: ^3.3.1
  google_fonts: ^6.3.1
  flutter_native_splash: ^2.4.6
  get_it: ^8.2.0
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.1
  super_banners: ^0.0.1
  barcode_newland_flutter: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/jpg/
    - assets/images/png/
    - assets/images/svg/